In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
#from google.colab import files # type: ignore
#uploaded = files.upload()

Saving cardekho.csv to cardekho (1).csv

In [ ]:
df = pd.read_csv('cardekho.csv')
print(df)

                              name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol
...                            ...   ...            ...        ...     ...
8123             Hyundai i20 Magna  2013         320000     110000  Petrol
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel
8126               Tata Indigo CR4  2013         290000      25000  Diesel
8127               Tata Indigo CR4  2013         290000      25000  Diesel

     seller_type transmission                 owner  mileage(km/ltr/kg)  \
0     Individual       Manual           First Owner               23.40
1     Individual       Manual          Second Owner               21.14
2     Individual       Manual           Third Owner               17.70
3     Individual       Manual           First Owner               23.00
4     Individual       Manual           First Owner               16.10
...          ...          ...                   ...                 ...
8123  Individual       Manual           First Owner               18.50
8124  Individual       Manual  Fourth & Above Owner               16.80
8125  Individual       Manual           First Owner               19.30
8126  Individual       Manual           First Owner               23.57
8127  Individual       Manual           First Owner               23.57

      engine max_power  seats
0     1248.0        74    5.0
1     1498.0    103.52    5.0
2     1497.0        78    5.0
3     1396.0        90    5.0
4     1298.0      88.2    5.0
...      ...       ...    ...
8123  1197.0     82.85    5.0
8124  1493.0       110    5.0
8125  1248.0      73.9    5.0
8126  1396.0        70    5.0
8127  1396.0        70    5.0

[8128 rows x 12 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                8128 non-null   object
 1   year                8128 non-null   int64
 2   selling_price       8128 non-null   int64
 3   km_driven           8128 non-null   int64
 4   fuel                8128 non-null   object
 5   seller_type         8128 non-null   object
 6   transmission        8128 non-null   object
 7   owner               8128 non-null   object
 8   mileage(km/ltr/kg)  7907 non-null   float64
 9   engine              7907 non-null   float64
 10  max_power           7913 non-null   object
 11  seats               7907 non-null   float64
dtypes: float64(3), int64(3), object(6)
memory usage: 762.1+ KB

In [ ]:
df.isnull().sum()

name                    0
year                    0
selling_price           0
km_driven               0
fuel                    0
seller_type             0
transmission            0
owner                   0
mileage(km/ltr/kg)    221
engine                221
max_power             215
seats                 221
dtype: int64

In [ ]:
df.dropna(inplace=True)
df.shape

(7907, 12)

In [ ]:
df.duplicated().sum()

1189

In [ ]:
df.drop_duplicates(inplace=True)
df.shape

(6718, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                6718 non-null   object
 1   year                6718 non-null   int64
 2   selling_price       6718 non-null   int64
 3   km_driven           6718 non-null   int64
 4   fuel                6718 non-null   object
 5   seller_type         6718 non-null   object
 6   transmission        6718 non-null   object
 7   owner               6718 non-null   object
 8   mileage(km/ltr/kg)  6718 non-null   float64
 9   engine              6718 non-null   float64
 10  max_power           6718 non-null   object
 11  seats               6718 non-null   float64
dtypes: float64(3), int64(3), object(6)
memory usage: 682.3+ KB

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
#data analysis

In [ ]:
for col in df.columns:
  print('Unique values of' + col)
  print(df[col].unique)
  print("=========================")

Unique values ofname
<bound method Series.unique of 0                  Maruti Swift Dzire VDI
1            Skoda Rapid 1.5 TDI Ambition
2                Honda City 2017-2020 EXi
3               Hyundai i20 Sportz Diesel
4                  Maruti Swift VXI BSIII
                      ...
8121    Maruti Wagon R VXI BS IV with ABS
8122           Hyundai i20 Magna 1.4 CRDi
8123                    Hyundai i20 Magna
8124                Hyundai Verna CRDi SX
8125               Maruti Swift Dzire ZDi
Name: name, Length: 6718, dtype: object>
=========================
Unique values ofyear
<bound method Series.unique of 0       2014
1       2014
2       2006
3       2010
4       2007
        ...
8121    2013
8122    2014
8123    2013
8124    2007
8125    2009
Name: year, Length: 6718, dtype: int64>
=========================
Unique values ofselling_price
<bound method Series.unique of 0       450000
1       370000
2       158000
3       225000
4       130000
         ...
8121    260000
8122    475000
8123    320000
8124    135000
8125    382000
Name: selling_price, Length: 6718, dtype: int64>
=========================
Unique values ofkm_driven
<bound method Series.unique of 0       145500
1       120000
2       140000
3       127000
4       120000
         ...
8121     50000
8122     80000
8123    110000
8124    119000
8125    120000
Name: km_driven, Length: 6718, dtype: int64>
=========================
Unique values offuel
<bound method Series.unique of 0       Diesel
1       Diesel
2       Petrol
3       Diesel
4       Petrol
         ...
8121    Petrol
8122    Diesel
8123    Petrol
8124    Diesel
8125    Diesel
Name: fuel, Length: 6718, dtype: object>
=========================
Unique values ofseller_type
<bound method Series.unique of 0       Individual
1       Individual
2       Individual
3       Individual
4       Individual
           ...
8121    Individual
8122    Individual
8123    Individual
8124    Individual
8125    Individual
Name: seller_type, Length: 6718, dtype: object>
=========================
Unique values oftransmission
<bound method Series.unique of 0       Manual
1       Manual
2       Manual
3       Manual
4       Manual
         ...
8121    Manual
8122    Manual
8123    Manual
8124    Manual
8125    Manual
Name: transmission, Length: 6718, dtype: object>
=========================
Unique values ofowner
<bound method Series.unique of 0                First Owner
1               Second Owner
2                Third Owner
3                First Owner
4                First Owner
                ...
8121            Second Owner
8122            Second Owner
8123             First Owner
8124    Fourth & Above Owner
8125             First Owner
Name: owner, Length: 6718, dtype: object>
=========================
Unique values ofmileage(km/ltr/kg)
<bound method Series.unique of 0       23.40
1       21.14
2       17.70
3       23.00
4       16.10
        ...
8121    18.90
8122    22.54
8123    18.50
8124    16.80
8125    19.30
Name: mileage(km/ltr/kg), Length: 6718, dtype: float64>
=========================
Unique values ofengine
<bound method Series.unique of 0       1248.0
1       1498.0
2       1497.0
3       1396.0
4       1298.0
         ...
8121     998.0
8122    1396.0
8123    1197.0
8124    1493.0
8125    1248.0
Name: engine, Length: 6718, dtype: float64>
=========================
Unique values ofmax_power
<bound method Series.unique of 0           74
1       103.52
2           78
3           90
4         88.2
         ...
8121      67.1
8122     88.73
8123     82.85
8124       110
8125      73.9
Name: max_power, Length: 6718, dtype: object>
=========================
Unique values ofseats
<bound method Series.unique of 0       5.0
1       5.0
2       5.0
3       5.0
4       5.0
       ...
8121    5.0
8122    5.0
8123    5.0
8124    5.0
8125    5.0
Name: seats, Length: 6718, dtype: float64>
=========================

In [ ]:
def get_brand_name(car_name):
  car_name = car_name.split(' ')[0]
  return car_name.strip()

  get_brand_name('Skoda Rapid 1.5 TDI Ambition')

In [ ]:
def clean_data(value):
  value = value.split('')[0]
  value = value.sprit()
  if value == '':
    value = 0
  return float(value)

In [ ]:
df['name'] = df['name'].apply(get_brand_name)
df['name'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel'], dtype=object)

AttributeError: 'int' object has no attribute 'split'

In [ ]:
for col in df.columns:
  print('Unique values of' + col)
  print(df[col].unique)
  print("=========================")

Unique values ofname
<bound method Series.unique of 0        Maruti
1         Skoda
2         Honda
3       Hyundai
4        Maruti
         ...
8121     Maruti
8122    Hyundai
8123    Hyundai
8124    Hyundai
8125     Maruti
Name: name, Length: 6718, dtype: object>
=========================
Unique values ofyear
<bound method Series.unique of 0       2014
1       2014
2       2006
3       2010
4       2007
        ...
8121    2013
8122    2014
8123    2013
8124    2007
8125    2009
Name: year, Length: 6718, dtype: int64>
=========================
Unique values ofselling_price
<bound method Series.unique of 0       450000
1       370000
2       158000
3       225000
4       130000
         ...
8121    260000
8122    475000
8123    320000
8124    135000
8125    382000
Name: selling_price, Length: 6718, dtype: int64>
=========================
Unique values ofkm_driven
<bound method Series.unique of 0       145500
1       120000
2       140000
3       127000
4       120000
         ...
8121     50000
8122     80000
8123    110000
8124    119000
8125    120000
Name: km_driven, Length: 6718, dtype: int64>
=========================
Unique values offuel
<bound method Series.unique of 0       Diesel
1       Diesel
2       Petrol
3       Diesel
4       Petrol
         ...
8121    Petrol
8122    Diesel
8123    Petrol
8124    Diesel
8125    Diesel
Name: fuel, Length: 6718, dtype: object>
=========================
Unique values ofseller_type
<bound method Series.unique of 0       Individual
1       Individual
2       Individual
3       Individual
4       Individual
           ...
8121    Individual
8122    Individual
8123    Individual
8124    Individual
8125    Individual
Name: seller_type, Length: 6718, dtype: object>
=========================
Unique values oftransmission
<bound method Series.unique of 0       Manual
1       Manual
2       Manual
3       Manual
4       Manual
         ...
8121    Manual
8122    Manual
8123    Manual
8124    Manual
8125    Manual
Name: transmission, Length: 6718, dtype: object>
=========================
Unique values ofowner
<bound method Series.unique of 0                First Owner
1               Second Owner
2                Third Owner
3                First Owner
4                First Owner
                ...
8121            Second Owner
8122            Second Owner
8123             First Owner
8124    Fourth & Above Owner
8125             First Owner
Name: owner, Length: 6718, dtype: object>
=========================
Unique values ofmileage(km/ltr/kg)
<bound method Series.unique of 0       23.40
1       21.14
2       17.70
3       23.00
4       16.10
        ...
8121    18.90
8122    22.54
8123    18.50
8124    16.80
8125    19.30
Name: mileage(km/ltr/kg), Length: 6718, dtype: float64>
=========================
Unique values ofengine
<bound method Series.unique of 0       1248.0
1       1498.0
2       1497.0
3       1396.0
4       1298.0
         ...
8121     998.0
8122    1396.0
8123    1197.0
8124    1493.0
8125    1248.0
Name: engine, Length: 6718, dtype: float64>
=========================
Unique values ofmax_power
<bound method Series.unique of 0           74
1       103.52
2           78
3           90
4         88.2
         ...
8121      67.1
8122     88.73
8123     82.85
8124       110
8125      73.9
Name: max_power, Length: 6718, dtype: object>
=========================
Unique values ofseats
<bound method Series.unique of 0       5.0
1       5.0
2       5.0
3       5.0
4       5.0
       ...
8121    5.0
8122    5.0
8123    5.0
8124    5.0
8125    5.0
Name: seats, Length: 6718, dtype: float64>
=========================

In [ ]:
df['name'].replace(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel'],
                   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], inplace=True)

<ipython-input-20-f99cff0a277e>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['name'].replace(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
<ipython-input-20-f99cff0a277e>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['name'].replace(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',

In [ ]:
df['transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [ ]:
df['transmission'].replace(['Manual', 'Automatic'],[1,2], inplace=True)

<ipython-input-22-e522b7676a60>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['transmission'].replace(['Manual', 'Automatic'],[1,2], inplace=True)
<ipython-input-22-e522b7676a60>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['transmission'].replace(['Manual', 'Automatic'],[1,2], inplace=True)

In [ ]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [ ]:
df['owner'].replace(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'],[1,2,3,4,5], inplace=True)

<ipython-input-24-4255c4e99203>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['owner'].replace(['First Owner', 'Second Owner', 'Third Owner',
<ipython-input-24-4255c4e99203>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['owner'].replace(['First Owner', 'Second Owner', 'Third Owner',

In [ ]:
df['seller_type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [ ]:
df['seller_type'].replace(['Individual', 'Dealer', 'Trustmark Dealer'],[1,2,3], inplace=True)

<ipython-input-26-30e2345df517>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['seller_type'].replace(['Individual', 'Dealer', 'Trustmark Dealer'],[1,2,3], inplace=True)
<ipython-input-26-30e2345df517>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['seller_type'].replace(['Individual', 'Dealer', 'Trustmark Dealer'],[1,2,3], inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                6718 non-null   int64
 1   year                6718 non-null   int64
 2   selling_price       6718 non-null   int64
 3   km_driven           6718 non-null   int64
 4   fuel                6718 non-null   object
 5   seller_type         6718 non-null   int64
 6   transmission        6718 non-null   int64
 7   owner               6718 non-null   int64
 8   mileage(km/ltr/kg)  6718 non-null   float64
 9   engine              6718 non-null   float64
 10  max_power           6718 non-null   object
 11  seats               6718 non-null   float64
dtypes: float64(3), int64(7), object(2)
memory usage: 682.3+ KB

In [ ]:
df['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [ ]:
df['fuel'].replace(['Diesel', 'Petrol', 'LPG', 'CNG'],[1,2,3,4], inplace=True)

<ipython-input-29-fd933b195e6d>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['fuel'].replace(['Diesel', 'Petrol', 'LPG', 'CNG'],[1,2,3,4], inplace=True)
<ipython-input-29-fd933b195e6d>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['fuel'].replace(['Diesel', 'Petrol', 'LPG', 'CNG'],[1,2,3,4], inplace=True)

In [ ]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,1,2014,450000,145500,1,1,1,1,23.40,1248.0,74,5.0
1,2,2014,370000,120000,1,1,1,2,21.14,1498.0,103.52,5.0
2,3,2006,158000,140000,2,1,1,3,17.70,1497.0,78,5.0
3,4,2010,225000,127000,1,1,1,1,23.00,1396.0,90,5.0
4,1,2007,130000,120000,2,1,1,1,16.10,1298.0,88.2,5.0

In [ ]:
print(df)

      name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0        1  2014         450000     145500     1            1             1
1        2  2014         370000     120000     1            1             1
2        3  2006         158000     140000     2            1             1
3        4  2010         225000     127000     1            1             1
4        1  2007         130000     120000     2            1             1
...    ...   ...            ...        ...   ...          ...           ...
8121     1  2013         260000      50000     2            1             1
8122     4  2014         475000      80000     1            1             1
8123     4  2013         320000     110000     2            1             1
8124     4  2007         135000     119000     1            1             1
8125     1  2009         382000     120000     1            1             1

      owner  mileage(km/ltr/kg)  engine max_power  seats
0         1               23.40  1248.0        74    5.0
1         2               21.14  1498.0    103.52    5.0
2         3               17.70  1497.0        78    5.0
3         1               23.00  1396.0        90    5.0
4         1               16.10  1298.0      88.2    5.0
...     ...                 ...     ...       ...    ...
8121      2               18.90   998.0      67.1    5.0
8122      2               22.54  1396.0     88.73    5.0
8123      1               18.50  1197.0     82.85    5.0
8124      4               16.80  1493.0       110    5.0
8125      1               19.30  1248.0      73.9    5.0

[6718 rows x 12 columns]

In [ ]:
input_data = df.drop(columns=['selling_price'])
output_data = df['selling_price']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.2, random_state=2)

In [ ]:
#model_creation

In [ ]:
model = LinearRegression()
# First, identify indices with NaN in x_train or y_train
nan_indices = x_train[x_train.isna().any(axis=1)].index.union(y_train[y_train.isna()].index)

# Drop those indices from both x_train and y_train
x_train = x_train.drop(nan_indices)
y_train = y_train.drop(nan_indices)

In [ ]:
print(len(x_train), len(y_train))

5373 5374

In [ ]:
# Drop rows with NaNs from both x_train and y_train
x_train = x_train.dropna().reset_index(drop=True)
y_train = y_train.dropna().reset_index(drop=True)

# Verify lengths
print("Length of x_train:", len(x_train))
print("Length of y_train:", len(y_train))

# Check if lengths now match
if len(x_train) == len(y_train):
    print("Datasets are aligned.")
else:
    # If they still don’t match, align explicitly by common indices
    common_indices = x_train.index.intersection(y_train.index)
    x_train = x_train.loc[common_indices].reset_index(drop=True)
    y_train = y_train.loc[common_indices].reset_index(drop=True)

Length of x_train: 5374
Length of y_train: 5374
Datasets are aligned.

In [ ]:
# Check for non-numeric values in x_train and y_train
print("Non-numeric values in x_train:")
print(x_train[~x_train.applymap(lambda x: isinstance(x, (int, float))).all(1)])

print("Non-numeric values in y_train:")
print(y_train[~y_train.apply(lambda x: isinstance(x, (int, float)))])

Non-numeric values in x_train:
      name  year  km_driven  fuel  seller_type  transmission  owner  \
0        8  2018      24000     1            2             1      1
1        7  2014     175000     1            1             1      1
2        9  2007     120000     1            1             1      2
3        1  2016      35000     2            1             1      1
4        3  2017      69000     1            2             1      1
...    ...   ...        ...   ...          ...           ...    ...
5369     1  2018      48000     1            2             1      1
5370     6  2018      20000     1            1             1      1
5371     5  2013      80000     1            1             1      1
5372     1  1997     186388     2            1             1      2
5373     9  2012     180000     1            1             1      1

      mileage(km/ltr/kg)  engine max_power  seats
0                  15.10  2179.0    152.87    7.0
1                  19.01  1461.0    108.45    5.0
2                  17.00  1405.0        70    5.0
3                  16.80   796.0      34.2    8.0
4                  25.60  1498.0      97.9    5.0
...                  ...     ...       ...    ...
5369               24.30  1248.0      88.5    5.0
5370               23.00  1498.0     98.96    5.0
5371               12.99  2494.0       100    7.0
5372               14.80  1298.0        80    8.0
5373               18.40  1248.0        75    5.0

[5374 rows x 11 columns]
Non-numeric values in y_train:
Series([], Name: selling_price, dtype: int64)

<ipython-input-52-14bdb9c79ef7>:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  print(x_train[~x_train.applymap(lambda x: isinstance(x, (int, float))).all(1)])

In [ ]:
# Replace empty strings or whitespace with NaN and then drop them
x_train = x_train.replace(r'^\s*$', float('nan'), regex=True).dropna().reset_index(drop=True)
y_train = y_train.replace(r'^\s*$', float('nan'), regex=True).dropna().reset_index(drop=True)

In [ ]:
# Verify lengths
print("Length of x_train:", len(x_train))
print("Length of y_train:", len(y_train))

# Fit the model if lengths match
if len(x_train) == len(y_train):
    model.fit(x_train, y_train)
else:
    print("Mismatch in lengths still exists.")

Length of x_train: 5373
Length of y_train: 5374
Mismatch in lengths still exists.

In [ ]:
# Align y_train with the indices of x_train
y_train = y_train.loc[x_train.index].reset_index(drop=True)

In [ ]:
# Check lengths again
print("Length of x_train:", len(x_train))
print("Length of y_train:", len(y_train))

# Fit the model if lengths match
if len(x_train) == len(y_train):
    model.fit(x_train, y_train)
else:
    print("There is still a length mismatch.")

Length of x_train: 5373
Length of y_train: 5373

In [ ]:
model.fit(x_train, y_train)

LinearRegression()

In [ ]:
predict = model.predict(x_test)
predict

array([ 265285.52123321,  407133.34031188,  397062.69485705, ...,
        547784.64577701,  817250.17481298, 1088455.27741915])

In [ ]:
x_train.head(1)

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,8,2018,24000,1,2,1,1,15.1,2179.0,152.87,7.0

In [ ]:
input_data_model = pd.DataFrame(
    [[8,2018,29000,1,2,1,1,15.1,2179.0,152.87,7.0]],
columns = ['name', 'year', 'km_driven', 'fuel', 'seller_type','transmission', 'owner', 'mileage(km/ltr/kg)', 'engine', 'max_power', 'seats'])

In [ ]:
input_data_model

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,8,2018,29000,1,2,1,1,15.1,2179.0,152.87,7.0

In [ ]:
#price_of_the_car

In [ ]:
model.predict(input_data_model)

array([932211.74316084])

In [ ]:
import pickle as pk
pk.dump(model, open('model.pkl', 'wb'))